services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root password for MySQL
    ports:
      - "3307:3306"  # Map host port 3307 to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent data storage
    networks:
      - my_network  # Custom network for communication with other services

  app:
    build:
      context: .  # Build the Docker image from the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile (optional if named Dockerfile)
    container_name: spring-boot-app
    ports:
      - "8300:8080"  # Map the application port
    depends_on:
      - mysql  # Ensure MySQL starts before the application
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container-2:3306/sys
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    networks:
      - my_network
    command: [ "./wait-for-it.sh", "mysql-container-2:3306", "--", "java", "-jar", "app.jar" ]  # Wait for MySQL


volumes:
  mysql_data:  # Define a volume for MySQL data persistence

networks:
  my_network:  # Define a custom network for service isolation
