name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        container_name: mysql-container-2
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - "3307:3306"
        volumes:
          - mysql_data:/var/lib/mysql
        networks:
          - my_network
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build  # This ensures tests run after the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

volumes:
  mysql_data:

networks:
  my_network:
