name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        options: --health-cmd="mysqladmin ping --silent"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        options: --health-cmd="mysqladmin ping --silent"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Download wait-for-it script
        run: wget https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh && chmod +x wait-for-it.sh

      - name: Wait for MySQL to be ready
        run: ./wait-for-it.sh mysql:3306 --timeout=30 --strict -- echo "MySQL is up"

      - name: Run Unit Tests
        run: mvn -B test --file pom.xml
